# create namespace
apiVersion: v1
kind: Namespace
metadata:
  name:  rez-devops

---
# create role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
# create service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  jenkins
  namespace: rez-devops

---
# create role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: rez-devops