kind: Service
apiVersion: v1
metadata:
  name:  jenkins-service
  namespace: rez-devops
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /
    prometheus.io/port:   '8080'
spec:
  selector:
    app:  jenkins-server
  type:  NodePort
  ports:
  - name:  jenkins-port
    port:  8080
    targetPort: httpport
    nodePort: 32000